name: IPTV Source Checker

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  check-sources:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg curl
        # 验证关键工具
        ffprobe -version || { echo "FFprobe安装失败"; exit 1; }
        curl --version
    
    - name: Install Python dependencies
      run: pip install requests
    
    - name: Run checker
      run: python scripts/check_iptv.py
      timeout-minutes: 15
    
    - name: Commit and push changes
      run: |
        git diff --quiet data/iptv_data.json || {
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/iptv_data.json
          git commit -m "Auto update: $(date +'%Y-%m-%d %H:%M') Clean invalid sources [skip ci]"
          git push
        }
