name: IPTV Source Checker

on:
  schedule:
    - cron: '0 */6 * * *'  # 每天UTC时间0点运行
  workflow_dispatch:  # 允许手动触发

jobs:
  check-sources:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        
    - name: Install Python dependencies
      run: pip install requests
    
    - name: Run checker
      run: python scripts/check_iptv.py
    
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data/iptv_data.json
        git commit -m "Auto update: Clean invalid IPTV sources [skip ci]"
        git push
