name: Update Movies Data

on:
  schedule:
    - cron: '0 16 * * *'  # 北京时间 00:00 (UTC+8)
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
      TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies globally
        run: |
          npm install -g axios@1.6.7 cheerio@1.0.0-rc.12
          echo "Dependencies installed globally"

      - name: Setup data directory
        run: |
          mkdir -p data
          chmod 755 data

      - name: Backup current data
        run: |
          if [ -f data/movies-data.json ]; then
            cp -v data/movies-data.json data/movies-data.backup.json
            chmod 644 data/movies-data.backup.json
          fi

      - name: Update Movies data
        id: update
        run: |
          node scripts/update-movies-data.js
          chmod 644 data/movies-data.json
        continue-on-error: true

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code data/movies-data.json || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add data/movies-data.json
          git commit -m "Auto-update: Movies data $(date +'%Y-%m-%d')"
          git pull --rebase
          git push

      - name: Cleanup
        run: |
          rm -f data/movies-data.backup.json
